### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-node#1]
- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- fix README, package*, NOTICE/LICENSE
- ~~publish under `@marklogic-community`~~

**Comment by patrickmcelwee** [comment]
There is one unresolved PR in bitbucket lingering. I put some effort into resolving it today.

**Comment by grtjn** [comment]
@patrickmcelwee / @mariannemyers does anyone remember which PR is meant? I see 5 open PR's in BB..

**Comment by grtjn** [comment]
It would be good to go over and try to clean up all the branches, there are definitely too many. gitX or network view in github could help..

**Comment by grtjn** [comment]
I think we can safely close this one now..
