### ISSUE TITLE
Allow default view on CRUD

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-node#28]

**Comment by grtjn** [comment]
Almost certain there is an _default view option in latest dev code..

**Comment by grtjn** [comment]
See also #46

**Comment by mariannemyers** [comment]
@grtjn Not seeing a _default for search, but it is there for crud.  Do you want to include that for search, too?  I may need a hand with that since you were the original author for that and better understand its intent.

**Comment by grtjn** [comment]
Right, I forgot this ticket is about both Crud and Search. Is there any support for views or action at all in Search yet?

**Comment by mariannemyers** [comment]
@grtjn None in Search yet

**Comment by grtjn** [comment]
Lets kick this out of r1.1 then.. ;)

**Comment by mariannemyers** [comment]
Added #48 for the search work

**Comment by grtjn** [comment]
That works too.. :)
