### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by dalaidunc** [marklogic-community/grove-node#40]
Running `npm run test` results in failures, from the crud.test.js file.

e.g.:

  1) defaultCrudRoute
       with CRUD server
         allows config of default view transform:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/grove-node/test/grove-default-routes/crud.test.js)
      at listOnTimeout (internal/timers.js:537:17)
      at processTimers (internal/timers.js:481:7)

**Comment by mariannemyers** [comment]
Fixed with commit 196ddb53cc320cfe703c2a7cd52082116809f7bc 

https://github.com/marklogic-community/grove-node/commit/196ddb53cc320cfe703c2a7cd52082116809f7bc
