### ISSUE TITLE
Update documentation to detail middle-tier HTTPS variables

### ISSUE THREAD

**Issue by mikeburl** [marklogic-community/grove-node#43]
When setting up a grove server to use SSL we were only to find documentation detailing the GROVE_ENABLE_HTTPS_IN_MIDDLETIER, GROVE_MIDDLETIER_SSLCERT, and GROVE_MIDDLETIER_SSLKEY variables in an internal bitbucket repo.  The documentation is out of date and suggests to point the SSLCERT variable at a .csr file, rather than the .crt file grove is actually expecting.

**Comment by mariannemyers** [comment]
Confirmed with @mikeburl that he mistakenly added .crt as working when .csr should be documented.  Will update the docs.

**Comment by grtjn** [comment]
Is this part of #46 yet or not? I did see a remark about PEM, but not about crt/csr..

**Comment by mariannemyers** [comment]
@grtjn Yes, the comment about PEM clarifies what is required by Node for certs.
