### ISSUE TITLE
Middle tier crashes when MarkLogic is busy and returns an error

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic-community/grove-node#8]
I think in search.js when trying to parse the response the middle tier crashes:
`            backend.call(req, reqOptions, function(backendResponse, data) {
              var json = JSON.parse(data.toString());
`

What's the best way to handle this?

**Comment by grtjn** [comment]
Ah, yes. Saw that before. Put a try catch around the parse, and just do data.toString in the catch part as failsafe..

**Comment by grtjn** [comment]
Sounds related to #38

**Comment by mariannemyers** [comment]
@grtjn This still problem still exists on the development branch.  
https://github.com/marklogic-community/grove-node/blob/development/grove-default-routes/search.js#L108

Is this what you had in mind?
```
                var json = {};
                try {
                  json = JSON.parse(data.toString());
                } catch (e) {
                  json = data.toString();
                }
```

**Comment by grtjn** [comment]
Yeah, looks right..

**Comment by mariannemyers** [comment]
@grtjn How can I test this one?  Seems like something in the search response from MarkLogic would need to have bad chars in it.

**Comment by grtjn** [comment]
perhaps try to break all.xml such that it validates but breaks on run.. snippet on json property `instance`?

**Comment by grtjn** [comment]
Can't really think of anything else, except timeout or crash..
